Parameters:
  DeliveryStreamName:
    Description: Enter the name for Kinesis Firehose delivery stream
    Type: String
  CheckpointTableName:
    Description: Enter the name for DynamoDB checkpoint table
    Type: String
  StagingS3BucketName:
    Description: Enter the name for S3 bucket used as staging area
    Type: String
  RedshiftConnectionString:
    Description: The Redshift JDBC connection string (e.g. jdbc:redshift://clustername.cuezkggje6fl.region.redshift.amazonaws.com:5439/databasename)
    Type: String
  RedshiftUsername:
    Description: The Redshift user name
    Type: String
  RedshiftPassword:
    Description: The Redshift user password
    Type: String
    NoEcho: true
  RedshiftDestinationTable:
    Description: The Redshift destination table
    Type: String
Resources:
  KinesisDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Ref DeliveryStreamName
      DeliveryStreamType: DirectPut
      RedshiftDestinationConfiguration:
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref CloudWatchLogGroup
          LogStreamName: !Ref RedshiftDeliveryLogStream
        ClusterJDBCURL: !Ref RedshiftConnectionString
        Username: !Ref RedshiftUsername
        Password: !Ref RedshiftPassword
        CopyCommand:
          DataTableName: !Ref RedshiftDestinationTable
          CopyOptions:
            !Join
              - ""
              - - "json"
                - " "
                - "'"
                - "s3://"
                - !Ref StagingS3BucketName
                - "/redshift-jsonpaths.json"
                - "'"
                - " "
                - "region"
                - " "
                - "'"
                - !Ref 'AWS::Region'
                - "'"
                - "\n"
                - "timeformat 'YYYY-MM-DD HH:MI:SSZ'"
        RoleARN: !GetAtt KinesisDataDeliveryRole.Arn
        S3Configuration:
          BucketARN: !GetAtt S3StagingBucket.Arn
          RoleARN: !GetAtt KinesisDataDeliveryRole.Arn
          BufferingHints:
            IntervalInSeconds: 60
            SizeInMBs: 1
          CloudWatchLoggingOptions:
            Enabled: true
            LogGroupName: !Ref CloudWatchLogGroup
            LogStreamName: !Ref S3DeliveryLogStream
          CompressionFormat: UNCOMPRESSED
  S3StagingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref StagingS3BucketName
  CheckpointTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: DeliveryStreamName 
          AttributeType: S
      KeySchema:
        -
          AttributeName: DeliveryStreamName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: !Ref CheckpointTableName
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName:
        !Join
          - ''
          - - '/aws/kinesisfirehose/'
            - !Ref DeliveryStreamName
  RedshiftDeliveryLogStream:
    Type: AWS::Logs::LogStream
    Properties: 
      LogGroupName: !Ref CloudWatchLogGroup
      LogStreamName: RedshiftDelivery
  S3DeliveryLogStream:
    Type: AWS::Logs::LogStream
    Properties: 
      LogGroupName: !Ref CloudWatchLogGroup
      LogStreamName: S3Delivery
  KinesisDataDeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: firehouse_data_delivery_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:AbortMultipartUpload'
                  - 's3:GetBucketLocation'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:ListBucketMultipartUploads'
                  - 's3:PutObject'
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref StagingS3BucketName
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref StagingS3BucketName
                      - '/*'
              - Effect: Allow
                Action: 'logs:PutLogEvents'
                Resource: 
                - !Join 
                    - ''
                    - - 'arn:aws:logs:'
                      - !Ref 'AWS::Region'
                      - ':'
                      - !Ref 'AWS::AccountId'
                      - 'log-group:/aws/kinesisfirehose/'
                      - !Ref DeliveryStreamName
                      - ':log-stream:*'