Parameters:
  DeliveryStreamName:
    Description: Enter the name for Kinesis Firehose delivery stream
    Type: String
  DeliveryBucketName:
    Description: Enter the name for S3 destination bucket
    Type: String
  CheckpointTableName:
    Description: Enter the name for DynamoDB checkpoint table
    Type: String
Resources:
  KinesisDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Ref DeliveryBucketName
      DeliveryStreamType: DirectPut
      S3DestinationConfiguration:
        BucketARN: !GetAtt StreamDestinationBucket.Arn 
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 1
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref DeliveryStreamName
          LogStreamName: S3Delivery
        CompressionFormat: UNCOMPRESSED
        RoleARN: !GetAtt KinesisDataDeliveryRole.Arn
  StreamDestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DeliveryBucketName
  CheckpointTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: DeliveryStreamName 
          AttributeType: S
      KeySchema:
        -
          AttributeName: DeliveryStreamName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: !Ref CheckpointTableName
  KinesisDataDeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: firehouse_data_delivery_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:AbortMultipartUpload'
                  - 's3:GetBucketLocation'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:ListBucketMultipartUploads'
                  - 's3:PutObject'
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref StreamDestinationBucket
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref StreamDestinationBucket
                      - '*'
              - Effect: Allow
                Action: 'logs:PutLogEvents'
                Resource: 
                - !Join 
                    - ''
                    - - 'arn:aws:logs:'
                      - !Ref 'AWS::Region'
                      - ':'
                      - !Ref 'AWS::AccountId'
                      - 'log-group:/aws/kinesisfirehose/'
                      - !Ref DeliveryStreamName
                      - ':log-stream:*'